api:
  id: "18581275"  

request:
  host: "0.0.0.0"
  port: "8083"
  
https:
  host: "0.0.0.0"
  port: "8084"

consume:
  location: "http://dneonline.com/calculator.asmx?wsdl"
  service: "Calculator"
  port: "CalculatorSoap"
  address: "http://dneonline.com/calculator.asmx"
tls:
  type: "JKS"
  path: "Prowess-SSL-Keystore.jks"
  alias: "*.esb.internal.prowess.com"
  keypassword: test123
  password: test123

listener:
  path: "/api/*"

console:
  path: "/console/*"